services:
  back-end:
    container_name: back-end
    build:
      context: ./back-end
      target: prod
    environment:
      - DATABASE_URL="postgres://postgres:password@base:5432/postgres"
      - NODE_ENV=production
      - CACHE_URL=redis://cache
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 4000

  web-app:
    container_name: web-app
    build:
      context: ./web-app
      target: prod
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  database:
    container_name: database
    image: postgis/postgis:15-3.4
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U postgres

  gateway:
    container_name: gateway
    image: nginx
    depends_on:
      - back-end
      - web-app
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  cache:
    container_name: cache
    image: redis

volumes:
  database-data:
