export enum SideBarContentEnum {
  NO_CONTENT = "NO_CONTENT",
  FAVORITES = "FAVORITES",
  FAVORITES_BY_CATEGORY = "FAVORITES_BY_CATEGORY",
  CREATE_PLACE = "CREATE_PLACE",
  CREATE_CATEGORY = "CREATE_CATEGORY",
  PLACE = "PLACE",
}
